version: "3"
name: mms_otm
services:
  backend:
    image: almyra/mms_be
    ports:
      - "1337:1337"
    depends_on:
      - postgres_db
    # command: --mountGraphQL --mountPlayground
    volumes:
      - ./files:/parse/files
      - ./logs:/parse/logs
    networks:
      - otm-network
  postgres_db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=armin
      - POSTGRES_PASSWORD=3031323334
      - POSTGRES_DB=mms_otm
    networks:
      - otm-network
    command: "./script.sh"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
networks:
  otm-network:
