  version: '3'
  name: mms_otm
  services:
    backend:
      build: .
      ports:
        - '3000:3000'
      depends_on:
        - postgres_db
        - parse-server
      networks:
      - otm-network
    parse-dashboard:
      image: parseplatform/parse-dashboard
      depends_on:
        - postgres_db
        - parse-server
      ports:
        - 4040:4040
      environment:
        PARSE_DASHBOARD_TRUST_PROXY: undefined // Or "1" to trust connection info from a proxy's X-Forwarded-* headers
        PARSE_DASHBOARD_SERVER_URL: "http://localhost:1337/parse"
        PARSE_DASHBOARD_MASTER_KEY: "myMasterKey"
        PARSE_DASHBOARD_APP_ID: "myAppId"
        PARSE_DASHBOARD_APP_NAME: "MyApp"
        PARSE_DASHBOARD_USER_ID: "user1"
        PARSE_DASHBOARD_USER_PASSWORD: "pass"
        PARSE_DASHBOARD_SSL_KEY: "sslKey"
        PARSE_DASHBOARD_SSL_CERT: "sslCert"
        PARSE_DASHBOARD_CONFIG: undefined // Only for reference, it must not exist
        PARSE_DASHBOARD_COOKIE_SESSION_SECRET: undefined // set the cookie session secret, defaults to a random string. Use this option if you want sessions to work across multiple servers, or across restarts

    postgres_db:
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=armin
        - POSTGRES_PASSWORD=3031323334
        - POSTGRES_DB=mms_otm
      networks:
        - otm-network
      volumes:
        - postgres_data:/var/lib/postgresql/data
    parse-server:
      image: parseplatform/parse-server:latest
      environment:
        - PARSE_SERVER_APPLICATION_ID=myappid
        - PARSE_SERVER_MASTER_KEY=mymasterkey
        - PARSE_SERVER_DATABASE_URI=postgres://armin:3031323334@postgres:5432/mms_otm
        - PARSE_SERVER_URL=http://express:3000/parse
      volumes:
        - parse_data:/parse-server
      networks:
      - otm-network
  volumes:
    postgres_data:
    parse_data:
  networks:
    otm-network: